FROM nvidia/cuda:12.6.3-cudnn-devel-ubuntu24.04

# set timezone
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# set up mirrors
RUN <<EOF
tee /etc/apt/sources.list.d/ubuntu.sources <<-'EOF2'
Types: deb
URIs: https://mirrors.tuna.tsinghua.edu.cn/ubuntu
Suites: noble noble-updates noble-backports
Components: main restricted universe multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

Types: deb
URIs: http://security.ubuntu.com/ubuntu/
Suites: noble-security
Components: main restricted universe multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
EOF2
EOF

# Install dependencies
RUN <<EOF
apt-get update
apt-get install -y --no-install-recommends git build-essential cmake software-properties-common
apt-get clean
rm -rf /var/lib/apt/lists/*
EOF

# Clone hashcat
WORKDIR /root

RUN git clone https://github.com/hashcat/hashcat.git

WORKDIR /root/hashcat

RUN make -j $(nproc)

RUN make install

CMD ["tail", "-f", "/dev/null"]
